.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "LTT\-ARMALL" "1" "May 2010" "" ""
.
.SH "NAME"
\fBltt\-armall\fR \-\- manipulate system\-wide markers
.
.SH "SYNOPSIS"
\fBltt\-armall\fR [\fIoptions\fR]...
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Show summary of options.
.
.TP
\fB\-l\fR
Also activate locking markers (high traffic).
.
.TP
\fB\-n\fR
Also activate detailed network markers (large size).
.
.TP
\fB\-i\fR
Also activate input subsystem events (security implication: records
keyboard inputs).
.
.TP
\fB\-q\fR
Quiet mode, suppress output.
.
.SH "AUTHOR"
\fBltt\-armall\fR was written by Benjamin Poirier and Mathieu Desnoyers
<mathieu.desnoyers@efficios.com>
.
.P
This manual page was written by Jon Bernard <jbernard@debian.org>, for
the Debian project (and may be used by others).
