.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "LTT\-DISARMALL" "1" "May 2010" "" ""
.
.SH "NAME"
\fBltt\-disarmall\fR \-\- disconnect lttng markers
.
.SH "SYNOPSIS"
\fBltt\-disarmall\fR [\fIoptions\fR]...
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Show summary of options.
.
.TP
\fB\-q\fR
Quiet mode, suppress output.
.
.SH "AUTHOR"
\fBltt\-disarmall\fR was written by Benjamin Poirier and Mathieu Desnoyers
<mathieu.desnoyers@efficios.com>
.
.P
This manual page was written by Jon Bernard <jbernard@debian.org>, for
the Debian project (and may be used by others).
