.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "LTT\-ARMTAP" "1" "May 2010" "" ""
.
.SH "NAME"
\fBltt\-armtap\fR \-\- manipulate system\-wide taps
.
.SH "SYNOPSIS"
\fBltt\-armtap\fR [\fIevents\fR]
.
.SH "DESCRIPTION"
\fBltt\-armtap\fR will enable the system\-wide tap on the given list of events
passed as parameter, and stop the tap at each other "normal rate" events.
.
.SH "AUTHOR"
\fBltt\-armtap\fR was written by Mathieu Desnoyers
<mathieu.desnoyers@efficios.com>
.
.P
This manual page was written by Jon Bernard <jbernard@debian.org>, for
the Debian project (and may be used by others).
