.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "LTT\-DISARMTAP" "1" "May 2010" "" ""
.
.SH "NAME"
\fBltt\-disarmtap\fR \-\- disconnect function markers
.
.SH "SYNOPSIS"
\fBltt\-disarmtap\fR [\fIevents\fR]
.
.SH "DESCRIPTION"
\fBltt\-disarmtap\fR is a program that will disable the system\-wide tap on the
given list of events passed as parameter, and stop the tap at each other
"normal rate" events. Excluding core markers (already connected) and locking
markers (high traffic)
.
.SH "AUTHOR"
\fBltt\-disarmtap\fR was written by Mathieu Desnoyers
<mathieu.desnoyers@efficios.com>.
.
.P
This manual page was written by Jon Bernard <jbernard@debian.org>, for
the Debian project (and may be used by others).
